add ci to check simd is indeed in use.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -82,6 +82,29 @@ jobs:
                   npm ci;
                   npm run build;
                   npm run test;
+            # Install dependencies to check simd for builds
+            - name: Install wabt
+              run: |
+                  sudo apt install wabt;
+            # Check simd for rust builds
+            - name: Check 2d simd rust build
+              run: |
+                  wasm-objdump -d builds/rapier2d/pkg/rapier_wasm2d_bg.wasm | grep :\\sfd
+                  || >&2 echo "ERROR: 2d simd compat build does not include simd opcode prefix." && exit 1
+            - name: Check 3d simd compat build
+              run: |
+                  wasm-objdump -d builds/rapier3d/pkg/rapier_wasm3d_bg.wasm | grep :\\sfd
+                  || >&2 echo "ERROR: 3d simd compat build does not include simd opcode prefix." && exit 1
+            # Check simd for compat builds
+            - name: Check 2d simd compat build
+              run: |
+                  wasm-objdump -d rapier-compat/builds/2d-simd/wasm-build/rapier_wasm2d_bg.wasm | grep :\\sfd
+                  || >&2 echo "ERROR: 2d simd compat build does not include simd opcode prefix." && exit 1
+            - name: Check 3d simd compat build
+              run: |
+                  wasm-objdump -d rapier-compat/builds/3d-simd/wasm-build/rapier_wasm3d_bg.wasm | grep :\\sfd
+                  || >&2 echo "ERROR: 3d simd compat build does not include simd opcode prefix." && exit 1
+            # Upload
             - uses: actions/upload-artifact@v4
               with:
                   name: pkg ${{ matrix.os }}
